### ISSUE TITLE
Bot token exposed

### ISSUE THREAD

**Issue by ghost** [discordsheep/discordticket#2]
Uhh, @pgamerxdev, be careful in the future. Your token is literally revealed in the config.json. 

![image](https://user-images.githubusercontent.com/57224016/106848300-b0317d80-66d6-11eb-8b60-6a93addfaf25.png)
Please act quickly!

**Comment by CodeWithSwastik** [comment]
I'm pretty sure discord auto regens the token if it gets leaked like this so no worries :)

**Comment by pgamerx** [comment]
> I'm pretty sure discord auto regens the token if it gets leaked like this so no worries :)

YUS 
You are correct :pog:
